# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='bms',
    version='0.1.0',
    python_requires='==3.*,>=3.6.0',
    author='elferia',
    author_email='a.t.qu.qu.qu@gmail.com',
    entry_points={"console_scripts": ["bms = bms.bms:bms"]},
    packages=['bms'],
    package_dir={"": "."},
    package_data={"bms": ["*.ini"]},
    install_requires=['click==7.*,>=7.0.0', 'requests==2.*,>=2.22.0'],
    extras_require={"dev": ["autopep8==1.*,>=1.5.0", "pytest==5.*,>=5.2.0"]},
)
